name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/frontend-app-main.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    with:
      serviceName: ${GITHUB_REPOSITORY#*/}
      prodReplicas: 15
