name: branch
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/frontend-library-branch.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
