name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/frontend/shareable-branch.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  release:
    uses: usafacts/github-workflows/frontend/shareable-main.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
