name: autoupdate-minor
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/frontend-npm-autoupdate-minor.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
