name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/frontend-library-branch.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  release:
    needs: test
    uses: usafacts/github-workflows/.github/workflows/frontend-library-main.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
