name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  container:
    uses: usafacts/github-workflows/.github/workflows/frontend-app-container.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    with:
      serviceName: ${{ github.event.repository.name }}
