name: main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/backend-service-test.yml@main
  container:
    uses: usafacts/github-workflows/.github/workflows/backend-service-container.yml@main
    needs: [ test ]
    secrets:
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    with:
      serviceName: "${GITHUB_REPOSITORY#*/}"