name: main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    uses: usafacts/github-workflows/.github/workflows/backend-library-test.yml@main
  publish:
    uses: usafacts/github-workflows/.github/workflows/backend-library-publish.yml@main
    needs: [ test ]
    secrets:
      GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
