name: main
on:
  push:
    branches: [main]
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  release:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
          token: ${{secrets.GIT_TOKEN}}
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Version
        run: |
          git config --global user.email "pipeline@usafacts.org"
          git config --global user.name "Github Pipeline"
          npm version patch -m "ci(build): Bump package from $(npm info . version) to %s [skip ci]" --force
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm run test
      - name: Test
        run: npm run build
      - name: NPM
        run: npm publish
        # We reset and clean the local env because it can contain changes from `npm install` that we don't want.
        # The version bump from `npm version patch` created a commit already. Nothing else needs to be committed.
      - name: VersionSave
        id: versionsave
        run: |
          git reset --hard
          git clean -f -d
          git push --follow-tags --force
        continue-on-error: true
        # If the `versionsave` step fails, we want to try to rollback the push we did for NPM prior to that.
        # TODO - This doesn't actually work - I'm not sure if our tokens have access to unpublish commands.
      - name: NPM-Rollback
        if: ${{ steps.versionsave.outcome == 'failure' }}
        run: |
          npm unpublish $(npm info . name)@$(npm info . version) --force
        continue-on-error: true
      - name: Storybook
        if: ${{ steps.versionsave.outcome != 'failure' }}
        continue-on-error: true
        run: |
          npm run build-storybook
          usafacts azsync --source "${GITHUB_WORKSPACE}/storybook-static" --container "storybook/${GITHUB_REPOSITORY#*/}"
