name: main
on:
  workflow_call:
    secrets:
      GIT_TOKEN:
        required: true
    inputs:
      version:
        description: "What version to make a release from"
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  test:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Release
        uses: actions/github-script@v5.0.0
        with:
          script: |
            const tag = "${{inputs.cleanCheckout}}";
            await github.rest.repos.createRelease({
              ...context.repo,
              tag_name: tag,
            });
