name: "Combine PRs"
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
jobs:
  combine-prs:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: ${{inputs.cleanCheckout}}
          token: ${{secrets.GIT_TOKEN}}
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Auto Update
        run: |
          npx npm-check-updates /@usafacts/ --target minor -u
          npx npm-check-updates --target patch -u
      - name: Install
        run: npm install --legacy-peer-deps
      - name: Save
        run: |
          git reset --hard
          git clean -f -d
          git push --force
