name: branch
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
    inputs:
      cleanCheckout:
        description: "Whether to prefer a clean checkout (debug purposes)"
        default: "false"
        required: false
        type: boolean
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
# For now this is identical to library-branch but we'll have two files just in case we want to split off easily.
jobs:
  test:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: ${{inputs.cleanCheckout}}
          token: ${{secrets.GIT_TOKEN}}
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm run test
