name: branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
      TEST_URL:
        required: true
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  test:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
          token: ${{secrets.GIT_TOKEN}}
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install
        run: |
          npm install --legacy-peer-deps
          npm install -g @lhci/cli@0.8.x
      - name: Lighthouse
        run: |
          lhci collect --url ${{ secrets.TEST_URL }} --outputDir .lighthouse --reportFilenamePattern 'report.${{ secrets.TEST_URL }}.%%EXTENSION%%' --config ./node_modules/@usafacts/frontend-library-testing/.lighthouserc.js
      - name: Display
        run: cat .lighthouse/report.${{ secrets.TEST_URL }}.json
      - name: Results
        run: |
          node -p -e '\
            const report = JSON.parse(require("fs").readFileSync(".lighthouse/report.${{ secrets.TEST_URL }}.json")); \
            console.log(Object.keys(report.categories).reduce((acc,cat) => ({ ...acc, [cat]: report.categories[cat]?.score }), {}));'
